apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openjdk18-openshift-s2i
  spec:
    dockerImageRepository: "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"
