version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

  #redis:
  #  image: redis:alpine
  #  restart: always
  #  ports:
  #    - 6379:6379

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
    - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    #entrypoint:
    #  - /mysql-init.sh
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  cassandra:
    image: cassandra:latest
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./cassandra-init.sh:/docker-entrypoint2.sh:ro
    command: /docker-entrypoint2.sh
    ports:
      - 7199:7199
      - 9042:9042

  cassandra-web:
    image: ipushc/cassandra-web
    environment:
      - "CASSANDRA_HOST=cassandra"
      - "CASSANDRA_PORT=9042"
      - "HOST_PORT:80"
    restart: always
    depends_on:
      - "cassandra"
    ports:
      - 8092:8083

  adminer:
    image: adminer
    restart: always
    depends_on:
      - "mysql"
    ports:
      - 8090:8080

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    ports:
      - 8091:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  sysdig:
    container_name: sysdig
    privileged: true
    stdin_open: true
    tty: true
    image: sysdig/sysdig:latest
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
