version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
     #- ./nginx.conf:/etc/nginx/nginx.conf
     - ./nginx.conf:/etc/nginx/conf.d/nginx.template
    ports:
     - 80:80
     - 443:443
    environment:
     - NGINX_HOST=tibbes.com
     - NGINX_PORT=80
    command: /bin/ash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
