pipeline {
  agent any
  tools {
    jdk 'jdk8'
  }
  stages {
    stage('Clone repository') {
      steps {
        echo 'Checkout'
      }
    }
    stage('Build application') {
      steps {
        dir ('openshift/skeletor') {
          echo 'Build'
          sh 'pwd'
          sh './gradlew build'
        }
      }
    }
    stage('Test application') {
      steps {
        dir ('openshift/skeletor') {
          echo 'Test'
          sh 'pwd'
          sh './gradlew test'
        }
      }
    }
  }
  post {
    always {
      echo 'Bye bye'
    }
  }
}
