node ('maven') {
  stage('Clone repository') {
    checkout scm
  }
  stage('Build application') {
    dir ('openshift/skeletor') {
      echo 'Build'
      sh './gradlew build'
    }
  }
  stage('Test application') {
    dir ('openshift/skeletor') {
      echo 'Test'
      sh './gradlew test'
    }
  }
  stage('Build docker image') {
    dir ('openshift/skeletor') {
      echo 'Docker Build'
      sh "oc start-build skeletor-image --from-file=build/libs/skeletor-1.0.jar --follow"
    }
  }
}